---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: clusterdescriptions.intent.automation.dcn.ssu.ac.kr
spec:
  group: intent.automation.dcn.ssu.ac.kr
  names:
    kind: ClusterDescription
    listKind: ClusterDescriptionList
    plural: clusterdescriptions
    singular: clusterdescription
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: ClusterDescription is the Schema for the clusterdescriptions
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClusterDescriptionSpec defines the desired state of ClusterDescription
            properties:
              infrastructure:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "make" to regenerate code after modifying this file'
                items:
                  properties:
                    info:
                      description: 'INSERT ADDITIONAL SPEC FIELDS - desired state
                        of cluster Important: Run "make" to regenerate code after
                        modifying this file'
                      properties:
                        name:
                          description: Name of Blueprint
                          type: string
                        override:
                          additionalProperties:
                            type: string
                          description: Override field of blueprint
                          type: object
                        spec:
                          description: Spec
                      type: object
                    spec:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
                type: array
              software:
                items:
                  properties:
                    info:
                      description: 'INSERT ADDITIONAL SPEC FIELDS - desired state
                        of cluster Important: Run "make" to regenerate code after
                        modifying this file'
                      properties:
                        name:
                          description: Name of Blueprint
                          type: string
                        override:
                          additionalProperties:
                            type: string
                          description: Override field of blueprint
                          type: object
                        spec:
                          description: Spec
                      type: object
                    spec:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
                type: array
            type: object
          status:
            description: ClusterDescriptionStatus defines the observed state of ClusterDescription
            properties:
              status:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                type: string
            type: object
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
